#FeatherTips - Made by Zerek - Made for feather64.net

#How often should short format tips be broadcast to all of chat?
period: 24000

#What timezone should /servertime display? https://mkyong.com/java8/java-display-all-zoneid-and-its-utc-offset/
timezone: "Canada/Eastern"

AssTips:
  - "<#96d7f2>Ass Tip: Keep up to date on #announcements."
  - "<#96d7f2>Ass Tip: Keep up to date on #changelog."
  - "<#96d7f2>Ass Tip: Keep up to date on /tip"
  - "<#96d7f2>Ass Tip: Don't kill new players."
  - "<#96d7f2>Ass Tip: Focus on answering chat questions."
  - "<#96d7f2>Ass Tip: Help new players with info, not items!"
  - "<#96d7f2>Ass Tip: Don't be to toxic lmao."
  - "<#96d7f2>Ass Tip: Report possible exploits."
  - "<#96d7f2>Ass Tip: Don't call out vanished Mods/Admins."
  - "<#96d7f2>Ass Tip: /sc <message>"
  - "<#96d7f2>Ass Tip: Build the community."
  - "<#96d7f2>Ass Tip: /tip <tip> <player>"
  - "<#96d7f2>Ass Tip: /broadcast <tip>"
  - "<#96d7f2>Ass Tip: Hang in there!"
  - "<#96d7f2>Ass Tip: Don't trick players who trust you because of your role"
  - "<#96d7f2>Ass Tip: Combat spammers with /tip ignore or /broadcast ignore"
  - "<#96d7f2>Ass Tip: Teach how to find info instead of sending the info."
  - "<#96d7f2>Ass Tip: Be an ass_, but don't act like an ass."
  - "<#96d7f2>Ass Tip: Ask for clarification from other staff when needed."
  - "<#96d7f2>Ass Tip: Correct spreading of false information"
  - "<#96d7f2>Ass Tip: Assistants must be gay and autistic."
  - "<#96d7f2>Ass Tip: F64 players are allowed to be toxic."
  - "<#96d7f2>Ass Tip: Do not moderate, leave that to the mods/admins"
  - "<#96d7f2>Ass Tip: Ass (wo)man"
  - "<#96d7f2>Ass Tip: Assist players with info."
  - "<#96d7f2>Ass Tip: You are loved."
  - "<#96d7f2>Ass Tip: Support the bullied."
  - "<#96d7f2>Ass Tip: Be welcoming"
  - "<#96d7f2>Ass Tip: F64 is a Minecraft Community."
  - "<#96d7f2>Ass Tip: Try to keep an eye on chat."
  - "<#96d7f2>Ass Tip: Add your input to #staff channel."
  - "<#96d7f2>Ass Tip: Assistants must be active survival players."
  - "<#96d7f2>Ass Tip: Thanks for assisting."
  - "<#96d7f2>Ass Tip: Answer questions in #ask-staff-a-question."
  - "<#96d7f2>Ass Tip: Ask prefix I's how it's going."
  - "<#96d7f2>Ass Tip: Staff backup staff. Its the F64 way."
ModTips:
  - "<#8fe38c>Mod Tip: Focus on catching rule breakers."
  - "<#8fe38c>Mod Tip: /ban <player> <days>d <reason>"
  - "<#8fe38c>Mod Tip: /lookup <player> [ban date]"
  - "<#8fe38c>Mod Tip: Help assistants learn their role."
  - "<#8fe38c>Mod Tip: Ignore mod duties whenever you want."
  - "<#8fe38c>Mod Tip: Banning for jokes/admittance is for admins only."
  - "<#8fe38c>Mod Tip: Never ban unless you are 100% certain."
  - "<#8fe38c>Mod Tip: Mods raiding is discouraged since it can look... bad."
  - "<#8fe38c>Mod Tip: Consider how your PvP choices reflect on the server."
  - "<#8fe38c>Mod Tip: Backup staff 100% in public chats."
  - "<#8fe38c>Mod Tip: Encourage private reports from players."
  - "<#8fe38c>Mod Tip: Take your anger out on assistants."
  - "<#8fe38c>Mod Tip: Leave assistant duties for assistants when possible."
  - "<#8fe38c>Mod Tip: When you give directions, its LAW, be careful!"
  - "<#8fe38c>Mod Tip: KNOW THE RULES /rules"
  - "<#8fe38c>Mod Tip: /sc <message>"
  - "<#8fe38c>Mod Tip: /tip <tip> <player>"
  - "<#8fe38c>Mod Tip: /broadcast <tip>"
  - "<#8fe38c>Mod Tip: Avoid watching established players without reason."
  - "<#8fe38c>Mod Tip: Don't AnneTurtle"
  - "<#8fe38c>Mod Tip: Watching new players is an easy way to find hackers."
  - "<#8fe38c>Mod Tip: The admins will support your bans 100%"
  - "<#8fe38c>Mod Tip: Staff backup staff. Its the F64 way."