name: FeatherTips
version: '${project.version}'
main: com.zerek.feathertips.FeatherTips
api-version: 1.19
authors: [ Zerek ]
description: Tip system for feather64
commands:
  tip:
    description: Display long format tips to individuals (often yourself)
  tips:
    description: Display tip menu
  broadcast:
    description: Display short format tips to all online players
  servertime:
    description: Displays server time (ET)
